name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - run: ./gradlew -Pversion=${GITHUB_REF#refs/*/} build
    - if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew -Pversion=${GITHUB_REF#refs/*/} publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
